require:
  - rubocop-rails
  - rubocop-capybara

Rails/I18nLocaleTexts:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/MethodName:
 Exclude:
   - app/form_objects/*

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - db/*
    - db/migrate/*
    - bin/*
    - tmp/*
    - vendor/**/* # Used in github actions

Style/StringConcatenation:
  Enabled: false
Style/OpenStructUse:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Exclude:
    - 'config/initializers/simple_form_*.rb'

Style/Documentation:
  Exclude:
    - 'app/helpers/*.rb'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Lint/MissingSuper:
  Exclude:
    - 'app/services/*.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/*.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'Gemfile'
    - 'test/**/*'

Style/SymbolArray:
  Enabled: false

Style/RedundantFetchBlock:
  Exclude: 
    - 'config/puma.rb'

Style/GlobalStdStream:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/dashboards/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/Copyright:
  Notice: 'Copyright (© )?2[0-9]{3} .+'
  AutocorrectNotice: "# Copyright © 2023 Danil Pismenny <danil@brandymint.ru>\n"
  Description: 'Include a copyright notice in each file before any code.'
  Enabled: true
  # VersionAdded: '0.0.2'
